version: "3.8"
name: traefik_stack
services:

  traefik:
    image: "traefik:v3.0"
    container_name: "traefik"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dashboard.rule=Host(`traefik.${DOMAIN}`)"
      - "traefik.http.routers.dashboard.entrypoints=web"
      - "traefik.http.services.dashboard.loadbalancer.server.port=8080"

      # Only enable tls if we have a certificate in place!
      # - "traefik.http.routers.dashboard.tls"

  whoami:
    image: "traefik/whoami"
    container_name: "whoami"
    hostname: "whoami-dockbox2"
    ports:
      - 9999:80
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`${SUBDOMAIN_FOR_WHOAMI}.${DOMAIN}`)"
      - "traefik.http.routers.whoami.entrypoints=web"

      # Uncomment this section to have the main DOMAIN redirect to this container's subdomain
      # - "traefik.http.routers.domain.rule=Host(`${DOMAIN}`)"
      # - "traefik.http.routers.domain.middlewares=domain"
      # - 'traefik.http.middlewares.domain.redirectregex.regex=^[8](${DOMAIN}/)(.*)'
      # - 'traefik.http.middlewares.domain.redirectregex.replacement=[9](${SUBDOMAIN_FOR_WHOAMI}.${DOMAIN}/)$${1}'
      # - "traefik.http.middlewares.domain.redirectregex.permanent=true"

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.49.1
    container_name: cadvisor
    ports:
      - 8083:8080
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    depends_on:
      - dockerproxy
    environment:
      - DOCKER_HOST=tcp://dockerproxy:2375

  dockerproxy:
    image: tecnativa/docker-socket-proxy
    container_name: dockerproxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - CONTAINERS=1

  uptime-kuma:
    image: louislam/uptime-kuma:1.23.11-alpine
    container_name: "uptime-kuma"
    volumes:
      - uptime-kuma:/app/data
    ports:
      - 3001:3001
    depends_on:
      - dockerproxy
    environment:
      - DOCKER_HOST=tcp://dockerproxy:2375

volumes:
  uptime-kuma:

networks:
  default:
    name: ${DOCKER_PROXY_NETWORK}
    external: true
